#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

origin_url="https://github.com/AnJeongMin/docker-nginx-example.git" # 금지할 repo url

remote="$1"
url="$2"

if [ "$url" != "$origin_url" ]
then
    exit 0 # 실제 origin url이 아니면 그냥 push 됨
fi

#current_branch=$(git rev-parse --abbrev-ref HEAD)
current_bracnh="test"

if [ "$current_branch" == "main" -o "$current_branch" == "dev" ] # -a -> or
then
    echo "do not push in dev or main branch"
    exit 1
fi

cd server && yarn lint && yarn test

exit 0